// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Acceptance : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accepting_team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.IngTeam? AcceptingTeam { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.IngTeam AcceptingTeam { get; set; }
#endif
        /// <summary>The accepting_user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.TingUser? AcceptingUser { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.TingUser AcceptingUser { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The approval_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovalStatus { get; set; }
#nullable restore
#else
        public string ApprovalStatus { get; set; }
#endif
        /// <summary>The date_accepted property</summary>
        public double? DateAccepted { get; set; }
        /// <summary>The date_invalid property</summary>
        public double? DateInvalid { get; set; }
        /// <summary>The date_last_updated property</summary>
        public double? DateLastUpdated { get; set; }
        /// <summary>The reviews property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Review>? Reviews { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Review> Reviews { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Acceptance"/> and sets the default values.
        /// </summary>
        public Acceptance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Acceptance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Acceptance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Acceptance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepting_team", n => { AcceptingTeam = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.IngTeam>(global::Soenneker.Slack.OpenApiClient.Models.IngTeam.CreateFromDiscriminatorValue); } },
                { "accepting_user", n => { AcceptingUser = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.TingUser>(global::Soenneker.Slack.OpenApiClient.Models.TingUser.CreateFromDiscriminatorValue); } },
                { "approval_status", n => { ApprovalStatus = n.GetStringValue(); } },
                { "date_accepted", n => { DateAccepted = n.GetDoubleValue(); } },
                { "date_invalid", n => { DateInvalid = n.GetDoubleValue(); } },
                { "date_last_updated", n => { DateLastUpdated = n.GetDoubleValue(); } },
                { "reviews", n => { Reviews = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Review>(global::Soenneker.Slack.OpenApiClient.Models.Review.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.IngTeam>("accepting_team", AcceptingTeam);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.TingUser>("accepting_user", AcceptingUser);
            writer.WriteStringValue("approval_status", ApprovalStatus);
            writer.WriteDoubleValue("date_accepted", DateAccepted);
            writer.WriteDoubleValue("date_invalid", DateInvalid);
            writer.WriteDoubleValue("date_last_updated", DateLastUpdated);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Review>("reviews", Reviews);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
