// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper3"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccessoryElementType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper2? Button2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper2 Button2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper2? ChannelsSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper2 ChannelsSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper2? Checkboxes2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper2 Checkboxes2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper2? ConversationsSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper2 ConversationsSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper2? Datepicker2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper2 Datepicker2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper2? Datetimepicker2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper2 Datetimepicker2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper2? ExternalSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper2 ExternalSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper3? ImageWrapper3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper3 ImageWrapper3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper2? MultiChannelsSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper2 MultiChannelsSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper2? MultiConversationsSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper2 MultiConversationsSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper2? MultiExternalSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper2 MultiExternalSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper2? MultiStaticSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper2 MultiStaticSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper2? MultiUsersSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper2 MultiUsersSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper2? Overflow2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper2 Overflow2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper2? RadioButtons2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper2 RadioButtons2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper2? RichTextList2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper2 RichTextList2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper2? RichTextPreformatted2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper2 RichTextPreformatted2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper2? RichTextQuote2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper2 RichTextQuote2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper2? RichTextSection2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper2 RichTextSection2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper2? StaticSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper2 StaticSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper2? Timepicker2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper2 Timepicker2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper2? UsersSelect2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper2 UsersSelect2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper2? WorkflowButton2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper2 WorkflowButton2Wrapper2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.AccessoryElementType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.AccessoryElementType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.AccessoryElementType();
            result.Button2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper2();
            result.ChannelsSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper2();
            result.Checkboxes2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper2();
            result.ConversationsSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper2();
            result.Datepicker2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper2();
            result.Datetimepicker2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper2();
            result.ExternalSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper2();
            result.ImageWrapper3 = new global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper3();
            result.MultiChannelsSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper2();
            result.MultiConversationsSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper2();
            result.MultiExternalSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper2();
            result.MultiStaticSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper2();
            result.MultiUsersSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper2();
            result.Overflow2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper2();
            result.RadioButtons2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper2();
            result.RichTextList2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper2();
            result.RichTextPreformatted2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper2();
            result.RichTextQuote2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper2();
            result.RichTextSection2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper2();
            result.StaticSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper2();
            result.Timepicker2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper2();
            result.UsersSelect2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper2();
            result.WorkflowButton2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Button2Wrapper2 != null || ChannelsSelect2Wrapper2 != null || Checkboxes2Wrapper2 != null || ConversationsSelect2Wrapper2 != null || Datepicker2Wrapper2 != null || Datetimepicker2Wrapper2 != null || ExternalSelect2Wrapper2 != null || ImageWrapper3 != null || MultiChannelsSelect2Wrapper2 != null || MultiConversationsSelect2Wrapper2 != null || MultiExternalSelect2Wrapper2 != null || MultiStaticSelect2Wrapper2 != null || MultiUsersSelect2Wrapper2 != null || Overflow2Wrapper2 != null || RadioButtons2Wrapper2 != null || RichTextList2Wrapper2 != null || RichTextPreformatted2Wrapper2 != null || RichTextQuote2Wrapper2 != null || RichTextSection2Wrapper2 != null || StaticSelect2Wrapper2 != null || Timepicker2Wrapper2 != null || UsersSelect2Wrapper2 != null || WorkflowButton2Wrapper2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(Button2Wrapper2, ChannelsSelect2Wrapper2, Checkboxes2Wrapper2, ConversationsSelect2Wrapper2, Datepicker2Wrapper2, Datetimepicker2Wrapper2, ExternalSelect2Wrapper2, ImageWrapper3, MultiChannelsSelect2Wrapper2, MultiConversationsSelect2Wrapper2, MultiExternalSelect2Wrapper2, MultiStaticSelect2Wrapper2, MultiUsersSelect2Wrapper2, Overflow2Wrapper2, RadioButtons2Wrapper2, RichTextList2Wrapper2, RichTextPreformatted2Wrapper2, RichTextQuote2Wrapper2, RichTextSection2Wrapper2, StaticSelect2Wrapper2, Timepicker2Wrapper2, UsersSelect2Wrapper2, WorkflowButton2Wrapper2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper2>(null, Button2Wrapper2, ChannelsSelect2Wrapper2, Checkboxes2Wrapper2, ConversationsSelect2Wrapper2, Datepicker2Wrapper2, Datetimepicker2Wrapper2, ExternalSelect2Wrapper2, ImageWrapper3, MultiChannelsSelect2Wrapper2, MultiConversationsSelect2Wrapper2, MultiExternalSelect2Wrapper2, MultiStaticSelect2Wrapper2, MultiUsersSelect2Wrapper2, Overflow2Wrapper2, RadioButtons2Wrapper2, RichTextList2Wrapper2, RichTextPreformatted2Wrapper2, RichTextQuote2Wrapper2, RichTextSection2Wrapper2, StaticSelect2Wrapper2, Timepicker2Wrapper2, UsersSelect2Wrapper2, WorkflowButton2Wrapper2);
        }
    }
}
#pragma warning restore CS0618
