// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccessoryType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper? Button2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper Button2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper? ChannelsSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper ChannelsSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper? Checkboxes2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper Checkboxes2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper? ConversationsSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper ConversationsSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper? Datepicker2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper Datepicker2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper? Datetimepicker2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper Datetimepicker2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper? ExternalSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper ExternalSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper2? ImageWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper2 ImageWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper? MultiChannelsSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper MultiChannelsSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper? MultiConversationsSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper MultiConversationsSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper? MultiExternalSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper MultiExternalSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper? MultiStaticSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper MultiStaticSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper? MultiUsersSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper MultiUsersSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper? Overflow2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper Overflow2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper? RadioButtons2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper RadioButtons2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper? RichTextList2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper RichTextList2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper? RichTextPreformatted2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper RichTextPreformatted2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper? RichTextQuote2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper RichTextQuote2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper? RichTextSection2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper RichTextSection2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper? StaticSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper StaticSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper? Timepicker2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper Timepicker2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper? UsersSelect2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper UsersSelect2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper? WorkflowButton2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper WorkflowButton2Wrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.AccessoryType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.AccessoryType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.AccessoryType();
            result.Button2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper();
            result.ChannelsSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect2Wrapper();
            result.Checkboxes2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.Checkboxes2Wrapper();
            result.ConversationsSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.ConversationsSelect2Wrapper();
            result.Datepicker2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.Datepicker2Wrapper();
            result.Datetimepicker2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.Datetimepicker2Wrapper();
            result.ExternalSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.ExternalSelect2Wrapper();
            result.ImageWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper2();
            result.MultiChannelsSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.MultiChannelsSelect2Wrapper();
            result.MultiConversationsSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelect2Wrapper();
            result.MultiExternalSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.MultiExternalSelect2Wrapper();
            result.MultiStaticSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.MultiStaticSelect2Wrapper();
            result.MultiUsersSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.MultiUsersSelect2Wrapper();
            result.Overflow2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.Overflow2Wrapper();
            result.RadioButtons2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.RadioButtons2Wrapper();
            result.RichTextList2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.RichTextList2Wrapper();
            result.RichTextPreformatted2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.RichTextPreformatted2Wrapper();
            result.RichTextQuote2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.RichTextQuote2Wrapper();
            result.RichTextSection2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.RichTextSection2Wrapper();
            result.StaticSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.StaticSelect2Wrapper();
            result.Timepicker2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.Timepicker2Wrapper();
            result.UsersSelect2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.UsersSelect2Wrapper();
            result.WorkflowButton2Wrapper = new global::Soenneker.Slack.OpenApiClient.Models.WorkflowButton2Wrapper();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Button2Wrapper != null || ChannelsSelect2Wrapper != null || Checkboxes2Wrapper != null || ConversationsSelect2Wrapper != null || Datepicker2Wrapper != null || Datetimepicker2Wrapper != null || ExternalSelect2Wrapper != null || ImageWrapper2 != null || MultiChannelsSelect2Wrapper != null || MultiConversationsSelect2Wrapper != null || MultiExternalSelect2Wrapper != null || MultiStaticSelect2Wrapper != null || MultiUsersSelect2Wrapper != null || Overflow2Wrapper != null || RadioButtons2Wrapper != null || RichTextList2Wrapper != null || RichTextPreformatted2Wrapper != null || RichTextQuote2Wrapper != null || RichTextSection2Wrapper != null || StaticSelect2Wrapper != null || Timepicker2Wrapper != null || UsersSelect2Wrapper != null || WorkflowButton2Wrapper != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(Button2Wrapper, ChannelsSelect2Wrapper, Checkboxes2Wrapper, ConversationsSelect2Wrapper, Datepicker2Wrapper, Datetimepicker2Wrapper, ExternalSelect2Wrapper, ImageWrapper2, MultiChannelsSelect2Wrapper, MultiConversationsSelect2Wrapper, MultiExternalSelect2Wrapper, MultiStaticSelect2Wrapper, MultiUsersSelect2Wrapper, Overflow2Wrapper, RadioButtons2Wrapper, RichTextList2Wrapper, RichTextPreformatted2Wrapper, RichTextQuote2Wrapper, RichTextSection2Wrapper, StaticSelect2Wrapper, Timepicker2Wrapper, UsersSelect2Wrapper, WorkflowButton2Wrapper);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Button2Wrapper>(null, Button2Wrapper, ChannelsSelect2Wrapper, Checkboxes2Wrapper, ConversationsSelect2Wrapper, Datepicker2Wrapper, Datetimepicker2Wrapper, ExternalSelect2Wrapper, ImageWrapper2, MultiChannelsSelect2Wrapper, MultiConversationsSelect2Wrapper, MultiExternalSelect2Wrapper, MultiStaticSelect2Wrapper, MultiUsersSelect2Wrapper, Overflow2Wrapper, RadioButtons2Wrapper, RichTextList2Wrapper, RichTextPreformatted2Wrapper, RichTextQuote2Wrapper, RichTextSection2Wrapper, StaticSelect2Wrapper, Timepicker2Wrapper, UsersSelect2Wrapper, WorkflowButton2Wrapper);
        }
    }
}
#pragma warning restore CS0618
