// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdminBarriersCreateArgumentsRestrictedSubjectsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper? AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2? AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2 AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3? AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3 AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItem();
            result.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper = new global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper();
            result.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2();
            result.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3 = new global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper != null || AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2 != null || AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper, AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2, AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper>(null, AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper, AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper2, AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3);
        }
    }
}
#pragma warning restore CS0618
