// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AdminBarriersCreateArgumentsRestrictedSubjectsItemWrapper3Value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "call")]
        #pragma warning disable CS1591
        Call,
        #pragma warning restore CS1591
    }
}
