// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentsConversationsGetCanvasResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The canvas_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanvasId { get; set; }
#nullable restore
#else
        public string CanvasId { get; set; }
#endif
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Comment>? Comments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Comment> Comments { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The has_more_comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponseAllOf2HasMoreComments? HasMoreComments { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponseAllOf2HasMoreComments HasMoreComments { get; set; }
#endif
        /// <summary>The needed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Needed { get; set; }
#nullable restore
#else
        public string Needed { get; set; }
#endif
        /// <summary>The ok property</summary>
        public bool? Ok { get; set; }
        /// <summary>The provided property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provided { get; set; }
#nullable restore
#else
        public string Provided { get; set; }
#endif
        /// <summary>The response_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata? ResponseMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata ResponseMetadata { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The warning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Warning { get; set; }
#nullable restore
#else
        public string Warning { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponse"/> and sets the default values.
        /// </summary>
        public AgentsConversationsGetCanvasResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canvas_id", n => { CanvasId = n.GetStringValue(); } },
                { "comments", n => { Comments = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Comment>(global::Soenneker.Slack.OpenApiClient.Models.Comment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "has_more_comments", n => { HasMoreComments = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponseAllOf2HasMoreComments>(global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponseAllOf2HasMoreComments.CreateFromDiscriminatorValue); } },
                { "needed", n => { Needed = n.GetStringValue(); } },
                { "ok", n => { Ok = n.GetBoolValue(); } },
                { "provided", n => { Provided = n.GetStringValue(); } },
                { "response_metadata", n => { ResponseMetadata = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>(global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "warning", n => { Warning = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("canvas_id", CanvasId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Comment>("comments", Comments);
            writer.WriteStringValue("content", Content);
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.AgentsConversationsGetCanvasResponseAllOf2HasMoreComments>("has_more_comments", HasMoreComments);
            writer.WriteStringValue("needed", Needed);
            writer.WriteBoolValue("ok", Ok);
            writer.WriteStringValue("provided", Provided);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>("response_metadata", ResponseMetadata);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("warning", Warning);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
