// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>Type of the bookmark. Only `link` is supported at the moment.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BookmarksAddArgumentsType
    {
        [EnumMember(Value = "link")]
        #pragma warning disable CS1591
        Link,
        #pragma warning restore CS1591
    }
}
