// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Bookmark : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The app_action_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppActionId { get; set; }
#nullable restore
#else
        public string AppActionId { get; set; }
#endif
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelId { get; set; }
#nullable restore
#else
        public string ChannelId { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public double? DateCreated { get; set; }
        /// <summary>The date_updated property</summary>
        public double? DateUpdated { get; set; }
        /// <summary>The emoji property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Emoji { get; set; }
#nullable restore
#else
        public string Emoji { get; set; }
#endif
        /// <summary>The entity_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>The icon_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconUrl { get; set; }
#nullable restore
#else
        public string IconUrl { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last_updated_by_team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedByTeamId { get; set; }
#nullable restore
#else
        public string LastUpdatedByTeamId { get; set; }
#endif
        /// <summary>The last_updated_by_user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedByUserId { get; set; }
#nullable restore
#else
        public string LastUpdatedByUserId { get; set; }
#endif
        /// <summary>The link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Link { get; set; }
#nullable restore
#else
        public string Link { get; set; }
#endif
        /// <summary>The rank property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rank { get; set; }
#nullable restore
#else
        public string Rank { get; set; }
#endif
        /// <summary>The shortcut_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortcutId { get; set; }
#nullable restore
#else
        public string ShortcutId { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Bookmark"/> and sets the default values.
        /// </summary>
        public Bookmark()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Bookmark"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Bookmark CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Bookmark();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_action_id", n => { AppActionId = n.GetStringValue(); } },
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "channel_id", n => { ChannelId = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDoubleValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDoubleValue(); } },
                { "emoji", n => { Emoji = n.GetStringValue(); } },
                { "entity_id", n => { EntityId = n.GetStringValue(); } },
                { "icon_url", n => { IconUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "last_updated_by_team_id", n => { LastUpdatedByTeamId = n.GetStringValue(); } },
                { "last_updated_by_user_id", n => { LastUpdatedByUserId = n.GetStringValue(); } },
                { "link", n => { Link = n.GetStringValue(); } },
                { "rank", n => { Rank = n.GetStringValue(); } },
                { "shortcut_id", n => { ShortcutId = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_action_id", AppActionId);
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("channel_id", ChannelId);
            writer.WriteDoubleValue("date_created", DateCreated);
            writer.WriteDoubleValue("date_updated", DateUpdated);
            writer.WriteStringValue("emoji", Emoji);
            writer.WriteStringValue("entity_id", EntityId);
            writer.WriteStringValue("icon_url", IconUrl);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("last_updated_by_team_id", LastUpdatedByTeamId);
            writer.WriteStringValue("last_updated_by_user_id", LastUpdatedByUserId);
            writer.WriteStringValue("link", Link);
            writer.WriteStringValue("rank", Rank);
            writer.WriteStringValue("shortcut_id", ShortcutId);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
