// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChannelsSelect : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>&quot;: An identifier for this action. You can use this when you receive an interaction payload to[identify the source of the action](https://docs.slack.dev/interactivity/handling-user-interaction#payloads). Should be uniqueamong all other `action_id`s in the containing block. Maximum length for this field is 255 characters.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionId { get; set; }
#nullable restore
#else
        public string ActionId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The confirm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog? Confirm { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog Confirm { get; set; }
#endif
        /// <summary>Indicates whether the element will be set to auto focus within the[`view` object](https://docs.slack.dev/surfaces/modals). Only one element can be set to `true`.Defaults to `false`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectFocusOnLoad? FocusOnLoad { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectFocusOnLoad FocusOnLoad { get; set; }
#endif
        /// <summary>The ID of any valid public channel to be pre-selected when the menu loads.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitialChannel { get; set; }
#nullable restore
#else
        public string InitialChannel { get; set; }
#endif
        /// <summary>The placeholder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement? Placeholder { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement Placeholder { get; set; }
#endif
        /// <summary>When set to `true`, the [`view_submission` payload](https://docs.slack.dev/reference/interaction-payloads/view-interactions-payload#view_submission)from the menu&apos;s parent view will contain a `response_url`. This `response_url` can be used for[message responses](https://docs.slack.dev/interactivity/handling-user-interaction#message_responses). The target conversationfor the message will be determined by the value of this select menu.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectResponseUrlEnabled? ResponseUrlEnabled { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectResponseUrlEnabled ResponseUrlEnabled { get; set; }
#endif
        /// <summary>The type of element. In this case `type` is always `channels_select`.</summary>
        public global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect"/> and sets the default values.
        /// </summary>
        public ChannelsSelect()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelect();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_id", n => { ActionId = n.GetStringValue(); } },
                { "confirm", n => { Confirm = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog>(global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog.CreateFromDiscriminatorValue); } },
                { "focus_on_load", n => { FocusOnLoad = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectFocusOnLoad>(global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectFocusOnLoad.CreateFromDiscriminatorValue); } },
                { "initial_channel", n => { InitialChannel = n.GetStringValue(); } },
                { "placeholder", n => { Placeholder = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>(global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement.CreateFromDiscriminatorValue); } },
                { "response_url_enabled", n => { ResponseUrlEnabled = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectResponseUrlEnabled>(global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectResponseUrlEnabled.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action_id", ActionId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog>("confirm", Confirm);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectFocusOnLoad>("focus_on_load", FocusOnLoad);
            writer.WriteStringValue("initial_channel", InitialChannel);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>("placeholder", Placeholder);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectResponseUrlEnabled>("response_url_enabled", ResponseUrlEnabled);
            writer.WriteEnumValue<global::Soenneker.Slack.OpenApiClient.Models.ChannelsSelectType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
