// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The operation to perform on the canvas.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChangeWithContentOperation
    {
        [EnumMember(Value = "insert_at_start")]
        #pragma warning disable CS1591
        InsertAtStart,
        #pragma warning restore CS1591
        [EnumMember(Value = "insert_at_end")]
        #pragma warning disable CS1591
        InsertAtEnd,
        #pragma warning restore CS1591
    }
}
