// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Channel10 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The context_team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextTeamId { get; set; }
#nullable restore
#else
        public string ContextTeamId { get; set; }
#endif
        /// <summary>The created property</summary>
        public double? Created { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_archived property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsArchived? IsArchived { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsArchived IsArchived { get; set; }
#endif
        /// <summary>The is_im property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsIm? IsIm { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsIm IsIm { get; set; }
#endif
        /// <summary>The is_open property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOpen? IsOpen { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOpen IsOpen { get; set; }
#endif
        /// <summary>The is_org_shared property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOrgShared? IsOrgShared { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOrgShared IsOrgShared { get; set; }
#endif
        /// <summary>The last_read property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastRead { get; set; }
#nullable restore
#else
        public string LastRead { get; set; }
#endif
        /// <summary>The latest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Latest? Latest { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Latest Latest { get; set; }
#endif
        /// <summary>The priority property</summary>
        public double? Priority { get; set; }
        /// <summary>The unread_count property</summary>
        public double? UnreadCount { get; set; }
        /// <summary>The unread_count_display property</summary>
        public double? UnreadCountDisplay { get; set; }
        /// <summary>The updated property</summary>
        public double? Updated { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Channel10"/> and sets the default values.
        /// </summary>
        public Channel10()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Channel10"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Channel10 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Channel10();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context_team_id", n => { ContextTeamId = n.GetStringValue(); } },
                { "created", n => { Created = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_archived", n => { IsArchived = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsArchived>(global::Soenneker.Slack.OpenApiClient.Models.Channel10IsArchived.CreateFromDiscriminatorValue); } },
                { "is_im", n => { IsIm = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsIm>(global::Soenneker.Slack.OpenApiClient.Models.Channel10IsIm.CreateFromDiscriminatorValue); } },
                { "is_open", n => { IsOpen = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOpen>(global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOpen.CreateFromDiscriminatorValue); } },
                { "is_org_shared", n => { IsOrgShared = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOrgShared>(global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOrgShared.CreateFromDiscriminatorValue); } },
                { "last_read", n => { LastRead = n.GetStringValue(); } },
                { "latest", n => { Latest = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Latest>(global::Soenneker.Slack.OpenApiClient.Models.Latest.CreateFromDiscriminatorValue); } },
                { "priority", n => { Priority = n.GetDoubleValue(); } },
                { "unread_count", n => { UnreadCount = n.GetDoubleValue(); } },
                { "unread_count_display", n => { UnreadCountDisplay = n.GetDoubleValue(); } },
                { "updated", n => { Updated = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("context_team_id", ContextTeamId);
            writer.WriteDoubleValue("created", Created);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsArchived>("is_archived", IsArchived);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsIm>("is_im", IsIm);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOpen>("is_open", IsOpen);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Channel10IsOrgShared>("is_org_shared", IsOrgShared);
            writer.WriteStringValue("last_read", LastRead);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Latest>("latest", Latest);
            writer.WriteDoubleValue("priority", Priority);
            writer.WriteDoubleValue("unread_count", UnreadCount);
            writer.WriteDoubleValue("unread_count_display", UnreadCountDisplay);
            writer.WriteDoubleValue("updated", Updated);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
