// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConfirmationDialog : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The confirm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement? Confirm { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement Confirm { get; set; }
#endif
        /// <summary>The deny property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement? Deny { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement Deny { get; set; }
#endif
        /// <summary>Defines the color scheme applied to the `confirm` button. A value of `danger` will display the buttonwith a red background on desktop, or red text on mobile. A value of `primary` will display the button with a greenbackground on desktop, or blue text on mobile. If this field is not provided, the default value will be `primary`.</summary>
        public global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogStyle? Style { get; set; }
        /// <summary>A [PlainTextElement](PlainTextElement) text object that defines the explanatory text that appears in the confirmdialog. Maximum length for the `text` in this field is 300 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogText Text { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement? Title { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog"/> and sets the default values.
        /// </summary>
        public ConfirmationDialog()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "confirm", n => { Confirm = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>(global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement.CreateFromDiscriminatorValue); } },
                { "deny", n => { Deny = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>(global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement.CreateFromDiscriminatorValue); } },
                { "style", n => { Style = n.GetEnumValue<global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogStyle>(); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogText>(global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogText.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>(global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>("confirm", Confirm);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>("deny", Deny);
            writer.WriteEnumValue<global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogStyle>("style", Style);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConfirmationDialogText>("text", Text);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
