// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The type of block. For a context block, `type` is always `context`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContextBlockType
    {
        [EnumMember(Value = "context")]
        #pragma warning disable CS1591
        Context,
        #pragma warning restore CS1591
    }
}
