// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConversationsInviteSharedResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The conf_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfCode { get; set; }
#nullable restore
#else
        public string ConfCode { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The invite_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InviteId { get; set; }
#nullable restore
#else
        public string InviteId { get; set; }
#endif
        /// <summary>The is_legacy_shared_channel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponseAllOf2IsLegacySharedChannel? IsLegacySharedChannel { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponseAllOf2IsLegacySharedChannel IsLegacySharedChannel { get; set; }
#endif
        /// <summary>The needed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Needed { get; set; }
#nullable restore
#else
        public string Needed { get; set; }
#endif
        /// <summary>The ok property</summary>
        public bool? Ok { get; set; }
        /// <summary>The provided property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provided { get; set; }
#nullable restore
#else
        public string Provided { get; set; }
#endif
        /// <summary>The response_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata? ResponseMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata ResponseMetadata { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponse"/> and sets the default values.
        /// </summary>
        public ConversationsInviteSharedResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conf_code", n => { ConfCode = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "invite_id", n => { InviteId = n.GetStringValue(); } },
                { "is_legacy_shared_channel", n => { IsLegacySharedChannel = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponseAllOf2IsLegacySharedChannel>(global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponseAllOf2IsLegacySharedChannel.CreateFromDiscriminatorValue); } },
                { "needed", n => { Needed = n.GetStringValue(); } },
                { "ok", n => { Ok = n.GetBoolValue(); } },
                { "provided", n => { Provided = n.GetStringValue(); } },
                { "response_metadata", n => { ResponseMetadata = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>(global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("conf_code", ConfCode);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("invite_id", InviteId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConversationsInviteSharedResponseAllOf2IsLegacySharedChannel>("is_legacy_shared_channel", IsLegacySharedChannel);
            writer.WriteStringValue("needed", Needed);
            writer.WriteBoolValue("ok", Ok);
            writer.WriteStringValue("provided", Provided);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>("response_metadata", ResponseMetadata);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
