// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConversationsHistoryResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The channel_actions_count property</summary>
        public double? ChannelActionsCount { get; set; }
        /// <summary>The channel_actions_ts property</summary>
        public double? ChannelActionsTs { get; set; }
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The has_more property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponseAllOf2HasMore? HasMore { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponseAllOf2HasMore HasMore { get; set; }
#endif
        /// <summary>The latest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Latest { get; set; }
#nullable restore
#else
        public string Latest { get; set; }
#endif
        /// <summary>The messages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.MessageElement>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.MessageElement> Messages { get; set; }
#endif
        /// <summary>The needed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Needed { get; set; }
#nullable restore
#else
        public string Needed { get; set; }
#endif
        /// <summary>The ok property</summary>
        public bool? Ok { get; set; }
        /// <summary>The oldest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Oldest { get; set; }
#nullable restore
#else
        public string Oldest { get; set; }
#endif
        /// <summary>The pin_count property</summary>
        public double? PinCount { get; set; }
        /// <summary>The provided property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provided { get; set; }
#nullable restore
#else
        public string Provided { get; set; }
#endif
        /// <summary>The response_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata? ResponseMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata ResponseMetadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponse"/> and sets the default values.
        /// </summary>
        public ConversationsHistoryResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel_actions_count", n => { ChannelActionsCount = n.GetDoubleValue(); } },
                { "channel_actions_ts", n => { ChannelActionsTs = n.GetDoubleValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "has_more", n => { HasMore = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponseAllOf2HasMore>(global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponseAllOf2HasMore.CreateFromDiscriminatorValue); } },
                { "latest", n => { Latest = n.GetStringValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.MessageElement>(global::Soenneker.Slack.OpenApiClient.Models.MessageElement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "needed", n => { Needed = n.GetStringValue(); } },
                { "ok", n => { Ok = n.GetBoolValue(); } },
                { "oldest", n => { Oldest = n.GetStringValue(); } },
                { "pin_count", n => { PinCount = n.GetDoubleValue(); } },
                { "provided", n => { Provided = n.GetStringValue(); } },
                { "response_metadata", n => { ResponseMetadata = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>(global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("channel_actions_count", ChannelActionsCount);
            writer.WriteDoubleValue("channel_actions_ts", ChannelActionsTs);
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ConversationsHistoryResponseAllOf2HasMore>("has_more", HasMore);
            writer.WriteStringValue("latest", Latest);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.MessageElement>("messages", Messages);
            writer.WriteStringValue("needed", Needed);
            writer.WriteBoolValue("ok", Ok);
            writer.WriteStringValue("oldest", Oldest);
            writer.WriteDoubleValue("pin_count", PinCount);
            writer.WriteStringValue("provided", Provided);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>("response_metadata", ResponseMetadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
