// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConversationsSelectFilterIncludeItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "im")]
        #pragma warning disable CS1591
        Im,
        #pragma warning restore CS1591
        [EnumMember(Value = "mpim")]
        #pragma warning disable CS1591
        Mpim,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        PrivateValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        PublicValue,
        #pragma warning restore CS1591
    }
}
