// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DataTableBlock : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A string acting as a unique identifier for a block. If not specified, a `block_id` will be generated.You can use this `block_id` when you receive an interaction payload to[identify the source of the action](https://docs.slack.dev/interactivity/handling-user-interaction#payloads).Maximum length for this field is 255 characters. `block_id` should be unique for each message and each iteration ofa message. If a message is updated, use a new `block_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockId { get; set; }
#nullable restore
#else
        public string BlockId { get; set; }
#endif
        /// <summary>A caption for the table; used as the value for the HTML caption element.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Caption { get; set; }
#nullable restore
#else
        public string Caption { get; set; }
#endif
        /// <summary>Number of rows per page. Min `1`, Max `100`. Defaults to `5` if omitted.</summary>
        public double? PageSize { get; set; }
        /// <summary>The 0-based index of the column that uniquely identifies each row (the row header). This column is treated as the row&apos;s primary identifier for screen readers. Defaults to `0` if omitted.</summary>
        public double? RowHeaderColumnIndex { get; set; }
        /// <summary>An array consisting of table rows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Rows { get; set; }
#nullable restore
#else
        public UntypedNode Rows { get; set; }
#endif
        /// <summary>The type of block. For a data table block, `type` is always `data_table`.</summary>
        public global::Soenneker.Slack.OpenApiClient.Models.DataTableType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.DataTableBlock"/> and sets the default values.
        /// </summary>
        public DataTableBlock()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.DataTableBlock"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.DataTableBlock CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.DataTableBlock();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "block_id", n => { BlockId = n.GetStringValue(); } },
                { "caption", n => { Caption = n.GetStringValue(); } },
                { "page_size", n => { PageSize = n.GetDoubleValue(); } },
                { "row_header_column_index", n => { RowHeaderColumnIndex = n.GetDoubleValue(); } },
                { "rows", n => { Rows = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Slack.OpenApiClient.Models.DataTableType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("block_id", BlockId);
            writer.WriteStringValue("caption", Caption);
            writer.WriteDoubleValue("page_size", PageSize);
            writer.WriteDoubleValue("row_header_column_index", RowHeaderColumnIndex);
            writer.WriteObjectValue<UntypedNode>("rows", Rows);
            writer.WriteEnumValue<global::Soenneker.Slack.OpenApiClient.Models.DataTableType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
