// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Datepicker2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "datepicker")]
        #pragma warning disable CS1591
        Datepicker,
        #pragma warning restore CS1591
    }
}
