// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Datetimepicker2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "datetimepicker")]
        #pragma warning disable CS1591
        Datetimepicker,
        #pragma warning restore CS1591
    }
}
