// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DescriptionBlockElement3 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Accessory3? Accessory { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Accessory3 Accessory { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alt_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AltText { get; set; }
#nullable restore
#else
        public string AltText { get; set; }
#endif
        /// <summary>The app_collaborators property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AppCollaborators { get; set; }
#nullable restore
#else
        public List<string> AppCollaborators { get; set; }
#endif
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The author_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorName { get; set; }
#nullable restore
#else
        public string AuthorName { get; set; }
#endif
        /// <summary>The block_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockId { get; set; }
#nullable restore
#else
        public string BlockId { get; set; }
#endif
        /// <summary>The bot_user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BotUserId { get; set; }
#nullable restore
#else
        public string BotUserId { get; set; }
#endif
        /// <summary>The button_label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ButtonLabel { get; set; }
#nullable restore
#else
        public string ButtonLabel { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Description? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Description Description { get; set; }
#endif
        /// <summary>The developer_trace_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeveloperTraceId { get; set; }
#nullable restore
#else
        public string DeveloperTraceId { get; set; }
#endif
        /// <summary>The elements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Accessory3>? Elements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Accessory3> Elements { get; set; }
#endif
        /// <summary>The expand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Expand? Expand { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Expand Expand { get; set; }
#endif
        /// <summary>The fallback property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fallback { get; set; }
#nullable restore
#else
        public string Fallback { get; set; }
#endif
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement> Fields { get; set; }
#endif
        /// <summary>The function_trigger_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionTriggerId { get; set; }
#nullable restore
#else
        public string FunctionTriggerId { get; set; }
#endif
        /// <summary>The image_bytes property</summary>
        public double? ImageBytes { get; set; }
        /// <summary>The image_height property</summary>
        public double? ImageHeight { get; set; }
        /// <summary>The image_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageUrl { get; set; }
#nullable restore
#else
        public string ImageUrl { get; set; }
#endif
        /// <summary>The image_width property</summary>
        public double? ImageWidth { get; set; }
        /// <summary>The is_animated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsAnimated? IsAnimated { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsAnimated IsAnimated { get; set; }
#endif
        /// <summary>The is_workflow_app property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsWorkflowApp? IsWorkflowApp { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsWorkflowApp IsWorkflowApp { get; set; }
#endif
        /// <summary>The owning_team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwningTeamId { get; set; }
#nullable restore
#else
        public string OwningTeamId { get; set; }
#endif
        /// <summary>The provider_icon_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderIconUrl { get; set; }
#nullable restore
#else
        public string ProviderIconUrl { get; set; }
#endif
        /// <summary>The provider_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderName { get; set; }
#nullable restore
#else
        public string ProviderName { get; set; }
#endif
        /// <summary>The sales_home_workflow_app_type property</summary>
        public double? SalesHomeWorkflowAppType { get; set; }
        /// <summary>The share_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShareUrl { get; set; }
#nullable restore
#else
        public string ShareUrl { get; set; }
#endif
        /// <summary>The slack_file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.SlackFile2? SlackFile { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.SlackFile2 SlackFile { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement Text { get; set; }
#endif
        /// <summary>The thumbnail_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailUrl { get; set; }
#nullable restore
#else
        public string ThumbnailUrl { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Title? Title { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Title Title { get; set; }
#endif
        /// <summary>The title_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleUrl { get; set; }
#nullable restore
#else
        public string TitleUrl { get; set; }
#endif
        /// <summary>The trigger_subtype property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerSubtype { get; set; }
#nullable restore
#else
        public string TriggerSubtype { get; set; }
#endif
        /// <summary>The trigger_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerType { get; set; }
#nullable restore
#else
        public string TriggerType { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Type? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Type Type { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The video_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoUrl { get; set; }
#nullable restore
#else
        public string VideoUrl { get; set; }
#endif
        /// <summary>The workflow_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3"/> and sets the default values.
        /// </summary>
        public DescriptionBlockElement3()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessory", n => { Accessory = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Accessory3>(global::Soenneker.Slack.OpenApiClient.Models.Accessory3.CreateFromDiscriminatorValue); } },
                { "alt_text", n => { AltText = n.GetStringValue(); } },
                { "app_collaborators", n => { AppCollaborators = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "author_name", n => { AuthorName = n.GetStringValue(); } },
                { "block_id", n => { BlockId = n.GetStringValue(); } },
                { "bot_user_id", n => { BotUserId = n.GetStringValue(); } },
                { "button_label", n => { ButtonLabel = n.GetStringValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Description>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Description.CreateFromDiscriminatorValue); } },
                { "developer_trace_id", n => { DeveloperTraceId = n.GetStringValue(); } },
                { "elements", n => { Elements = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Accessory3>(global::Soenneker.Slack.OpenApiClient.Models.Accessory3.CreateFromDiscriminatorValue)?.AsList(); } },
                { "expand", n => { Expand = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Expand>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Expand.CreateFromDiscriminatorValue); } },
                { "fallback", n => { Fallback = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "function_trigger_id", n => { FunctionTriggerId = n.GetStringValue(); } },
                { "image_bytes", n => { ImageBytes = n.GetDoubleValue(); } },
                { "image_height", n => { ImageHeight = n.GetDoubleValue(); } },
                { "image_url", n => { ImageUrl = n.GetStringValue(); } },
                { "image_width", n => { ImageWidth = n.GetDoubleValue(); } },
                { "is_animated", n => { IsAnimated = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsAnimated>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsAnimated.CreateFromDiscriminatorValue); } },
                { "is_workflow_app", n => { IsWorkflowApp = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsWorkflowApp>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsWorkflowApp.CreateFromDiscriminatorValue); } },
                { "owning_team_id", n => { OwningTeamId = n.GetStringValue(); } },
                { "provider_icon_url", n => { ProviderIconUrl = n.GetStringValue(); } },
                { "provider_name", n => { ProviderName = n.GetStringValue(); } },
                { "sales_home_workflow_app_type", n => { SalesHomeWorkflowAppType = n.GetDoubleValue(); } },
                { "share_url", n => { ShareUrl = n.GetStringValue(); } },
                { "slack_file", n => { SlackFile = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.SlackFile2>(global::Soenneker.Slack.OpenApiClient.Models.SlackFile2.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement.CreateFromDiscriminatorValue); } },
                { "thumbnail_url", n => { ThumbnailUrl = n.GetStringValue(); } },
                { "title", n => { Title = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Title>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Title.CreateFromDiscriminatorValue); } },
                { "title_url", n => { TitleUrl = n.GetStringValue(); } },
                { "trigger_subtype", n => { TriggerSubtype = n.GetStringValue(); } },
                { "trigger_type", n => { TriggerType = n.GetStringValue(); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Type>(global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Type.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "video_url", n => { VideoUrl = n.GetStringValue(); } },
                { "workflow_id", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Accessory3>("accessory", Accessory);
            writer.WriteStringValue("alt_text", AltText);
            writer.WriteCollectionOfPrimitiveValues<string>("app_collaborators", AppCollaborators);
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("author_name", AuthorName);
            writer.WriteStringValue("block_id", BlockId);
            writer.WriteStringValue("bot_user_id", BotUserId);
            writer.WriteStringValue("button_label", ButtonLabel);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Description>("description", Description);
            writer.WriteStringValue("developer_trace_id", DeveloperTraceId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Accessory3>("elements", Elements);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Expand>("expand", Expand);
            writer.WriteStringValue("fallback", Fallback);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement>("fields", Fields);
            writer.WriteStringValue("function_trigger_id", FunctionTriggerId);
            writer.WriteDoubleValue("image_bytes", ImageBytes);
            writer.WriteDoubleValue("image_height", ImageHeight);
            writer.WriteStringValue("image_url", ImageUrl);
            writer.WriteDoubleValue("image_width", ImageWidth);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsAnimated>("is_animated", IsAnimated);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3IsWorkflowApp>("is_workflow_app", IsWorkflowApp);
            writer.WriteStringValue("owning_team_id", OwningTeamId);
            writer.WriteStringValue("provider_icon_url", ProviderIconUrl);
            writer.WriteStringValue("provider_name", ProviderName);
            writer.WriteDoubleValue("sales_home_workflow_app_type", SalesHomeWorkflowAppType);
            writer.WriteStringValue("share_url", ShareUrl);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.SlackFile2>("slack_file", SlackFile);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionElement>("text", Text);
            writer.WriteStringValue("thumbnail_url", ThumbnailUrl);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Title>("title", Title);
            writer.WriteStringValue("title_url", TitleUrl);
            writer.WriteStringValue("trigger_subtype", TriggerSubtype);
            writer.WriteStringValue("trigger_type", TriggerType);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElement3Type>("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("video_url", VideoUrl);
            writer.WriteStringValue("workflow_id", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
