// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.ActionsWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ContextWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.DividerWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper4"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Section2Wrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ShareShortcutWrapper2"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.VideoWrapper2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DescriptionBlockElementType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ActionsWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ActionsWrapper2? ActionsWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ActionsWrapper2 ActionsWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ContextWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ContextWrapper2? ContextWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ContextWrapper2 ContextWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.DividerWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DividerWrapper2? DividerWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DividerWrapper2 DividerWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper4? ImageWrapper4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper4 ImageWrapper4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextWrapper2? RichTextWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextWrapper2 RichTextWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Section2Wrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Section2Wrapper2? Section2Wrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Section2Wrapper2 Section2Wrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ShareShortcutWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ShareShortcutWrapper2? ShareShortcutWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ShareShortcutWrapper2 ShareShortcutWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.VideoWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.VideoWrapper2? VideoWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.VideoWrapper2 VideoWrapper2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElementType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElementType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.DescriptionBlockElementType();
            result.ActionsWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ActionsWrapper2();
            result.ContextWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ContextWrapper2();
            result.DividerWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.DividerWrapper2();
            result.ImageWrapper4 = new global::Soenneker.Slack.OpenApiClient.Models.ImageWrapper4();
            result.RichTextWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.RichTextWrapper2();
            result.Section2Wrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.Section2Wrapper2();
            result.ShareShortcutWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.ShareShortcutWrapper2();
            result.VideoWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.VideoWrapper2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ActionsWrapper2 != null || ContextWrapper2 != null || DividerWrapper2 != null || ImageWrapper4 != null || RichTextWrapper2 != null || Section2Wrapper2 != null || ShareShortcutWrapper2 != null || VideoWrapper2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ActionsWrapper2, ContextWrapper2, DividerWrapper2, ImageWrapper4, RichTextWrapper2, Section2Wrapper2, ShareShortcutWrapper2, VideoWrapper2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ActionsWrapper2>(null, ActionsWrapper2, ContextWrapper2, DividerWrapper2, ImageWrapper4, RichTextWrapper2, Section2Wrapper2, ShareShortcutWrapper2, VideoWrapper2);
        }
    }
}
#pragma warning restore CS0618
