// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DndEndSnoozeResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dnd_enabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2DndEnabled? DndEnabled { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2DndEnabled DndEnabled { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The needed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Needed { get; set; }
#nullable restore
#else
        public string Needed { get; set; }
#endif
        /// <summary>The next_dnd_end_ts property</summary>
        public double? NextDndEndTs { get; set; }
        /// <summary>The next_dnd_start_ts property</summary>
        public double? NextDndStartTs { get; set; }
        /// <summary>The ok property</summary>
        public bool? Ok { get; set; }
        /// <summary>The provided property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provided { get; set; }
#nullable restore
#else
        public string Provided { get; set; }
#endif
        /// <summary>The response_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata? ResponseMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata ResponseMetadata { get; set; }
#endif
        /// <summary>The snooze_enabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2SnoozeEnabled? SnoozeEnabled { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2SnoozeEnabled SnoozeEnabled { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponse"/> and sets the default values.
        /// </summary>
        public DndEndSnoozeResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dnd_enabled", n => { DndEnabled = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2DndEnabled>(global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2DndEnabled.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "needed", n => { Needed = n.GetStringValue(); } },
                { "next_dnd_end_ts", n => { NextDndEndTs = n.GetDoubleValue(); } },
                { "next_dnd_start_ts", n => { NextDndStartTs = n.GetDoubleValue(); } },
                { "ok", n => { Ok = n.GetBoolValue(); } },
                { "provided", n => { Provided = n.GetStringValue(); } },
                { "response_metadata", n => { ResponseMetadata = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>(global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata.CreateFromDiscriminatorValue); } },
                { "snooze_enabled", n => { SnoozeEnabled = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2SnoozeEnabled>(global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2SnoozeEnabled.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2DndEnabled>("dnd_enabled", DndEnabled);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("needed", Needed);
            writer.WriteDoubleValue("next_dnd_end_ts", NextDndEndTs);
            writer.WriteDoubleValue("next_dnd_start_ts", NextDndStartTs);
            writer.WriteBoolValue("ok", Ok);
            writer.WriteStringValue("provided", Provided);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>("response_metadata", ResponseMetadata);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.DndEndSnoozeResponseAllOf2SnoozeEnabled>("snooze_enabled", SnoozeEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
