// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntityEditSupport : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The hint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement? Hint { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement Hint { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportNumber? Number { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportNumber Number { get; set; }
#endif
        /// <summary>The optional property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportOptional? Optional { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportOptional Optional { get; set; }
#endif
        /// <summary>The placeholder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement? Placeholder { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement Placeholder { get; set; }
#endif
        /// <summary>The select property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportSelect? Select { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportSelect Select { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportText Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupport"/> and sets the default values.
        /// </summary>
        public EntityEditSupport()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "hint", n => { Hint = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>(global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement.CreateFromDiscriminatorValue); } },
                { "number", n => { Number = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportNumber>(global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportNumber.CreateFromDiscriminatorValue); } },
                { "optional", n => { Optional = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportOptional>(global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportOptional.CreateFromDiscriminatorValue); } },
                { "placeholder", n => { Placeholder = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>(global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement.CreateFromDiscriminatorValue); } },
                { "select", n => { Select = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportSelect>(global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportSelect.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportText>(global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportText.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>("hint", Hint);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportNumber>("number", Number);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportOptional>("optional", Optional);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlainTextElement>("placeholder", Placeholder);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportSelect>("select", Select);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityEditSupportText>("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
