// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Schema for the given entity type.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntityMetadataEntityPayload : IAdditionalDataHolder, IParsable
    {
        /// <summary>The actions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadActions? Actions { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadActions Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityAttributes? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityAttributes Attributes { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.EntityCustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.EntityCustomField> CustomFields { get; set; }
#endif
        /// <summary>The display_order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DisplayOrder { get; set; }
#nullable restore
#else
        public List<string> DisplayOrder { get; set; }
#endif
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadFields? Fields { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadFields Fields { get; set; }
#endif
        /// <summary>The slack_file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.FileEntitySlackFile? SlackFile { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.FileEntitySlackFile SlackFile { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayload"/> and sets the default values.
        /// </summary>
        public EntityMetadataEntityPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadActions>(global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadActions.CreateFromDiscriminatorValue); } },
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityAttributes>(global::Soenneker.Slack.OpenApiClient.Models.EntityAttributes.CreateFromDiscriminatorValue); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.EntityCustomField>(global::Soenneker.Slack.OpenApiClient.Models.EntityCustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "display_order", n => { DisplayOrder = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "fields", n => { Fields = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadFields>(global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadFields.CreateFromDiscriminatorValue); } },
                { "slack_file", n => { SlackFile = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.FileEntitySlackFile>(global::Soenneker.Slack.OpenApiClient.Models.FileEntitySlackFile.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadActions>("actions", Actions);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityAttributes>("attributes", Attributes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.EntityCustomField>("custom_fields", CustomFields);
            writer.WriteCollectionOfPrimitiveValues<string>("display_order", DisplayOrder);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityMetadataEntityPayloadFields>("fields", Fields);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.FileEntitySlackFile>("slack_file", SlackFile);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
