// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntityPresentDetailsArguments : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Error response preventing flexpane data from being returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsError Error { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityMetadata Metadata { get; set; }
#endif
        /// <summary>A reference to the original user action that initated the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerId { get; set; }
#nullable restore
#else
        public string TriggerId { get; set; }
#endif
        /// <summary>Set user_auth_required to true to indicate that the user must authenticate to view the full flexpane data. Defaults to false.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsUserAuthRequired? UserAuthRequired { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsUserAuthRequired UserAuthRequired { get; set; }
#endif
        /// <summary>&quot;A custom URL to which users are directed for authentication if required.Example: \&quot;https://example.com/onboarding?user_id=xxx\&quot;&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserAuthUrl { get; set; }
#nullable restore
#else
        public string UserAuthUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArguments"/> and sets the default values.
        /// </summary>
        public EntityPresentDetailsArguments()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArguments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArguments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArguments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsError>(global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsError.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityMetadata>(global::Soenneker.Slack.OpenApiClient.Models.EntityMetadata.CreateFromDiscriminatorValue); } },
                { "trigger_id", n => { TriggerId = n.GetStringValue(); } },
                { "user_auth_required", n => { UserAuthRequired = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsUserAuthRequired>(global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsUserAuthRequired.CreateFromDiscriminatorValue); } },
                { "user_auth_url", n => { UserAuthUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsError>("error", Error);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityMetadata>("metadata", Metadata);
            writer.WriteStringValue("trigger_id", TriggerId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.EntityPresentDetailsArgumentsUserAuthRequired>("user_auth_required", UserAuthRequired);
            writer.WriteStringValue("user_auth_url", UserAuthUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
