// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The type of block. For a feedback buttons block, `type` is always `feedback_buttons`.[Feedback buttons element reference](https://docs.slack.dev/reference/block-kit/block-elements/feedback-buttons-element).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FeedbackButtonsType
    {
        [EnumMember(Value = "feedback_buttons")]
        #pragma warning disable CS1591
        FeedbackButtons,
        #pragma warning restore CS1591
    }
}
