// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Function : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The callback_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackId { get; set; }
#nullable restore
#else
        public string CallbackId { get; set; }
#endif
        /// <summary>The category_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryId { get; set; }
#nullable restore
#else
        public string CategoryId { get; set; }
#endif
        /// <summary>The category_label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryLabel { get; set; }
#nullable restore
#else
        public string CategoryLabel { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public double? DateCreated { get; set; }
        /// <summary>The date_deleted property</summary>
        public double? DateDeleted { get; set; }
        /// <summary>The date_released property</summary>
        public double? DateReleased { get; set; }
        /// <summary>The date_updated property</summary>
        public double? DateUpdated { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The form_enabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.FunctionFormEnabled? FormEnabled { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.FunctionFormEnabled FormEnabled { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The input_parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.PutParameter>? InputParameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.PutParameter> InputParameters { get; set; }
#endif
        /// <summary>The output_parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.PutParameter>? OutputParameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.PutParameter> OutputParameters { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Function"/> and sets the default values.
        /// </summary>
        public Function()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Function"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Function CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Function();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "callback_id", n => { CallbackId = n.GetStringValue(); } },
                { "category_id", n => { CategoryId = n.GetStringValue(); } },
                { "category_label", n => { CategoryLabel = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDoubleValue(); } },
                { "date_deleted", n => { DateDeleted = n.GetDoubleValue(); } },
                { "date_released", n => { DateReleased = n.GetDoubleValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "form_enabled", n => { FormEnabled = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.FunctionFormEnabled>(global::Soenneker.Slack.OpenApiClient.Models.FunctionFormEnabled.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input_parameters", n => { InputParameters = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.PutParameter>(global::Soenneker.Slack.OpenApiClient.Models.PutParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "output_parameters", n => { OutputParameters = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.PutParameter>(global::Soenneker.Slack.OpenApiClient.Models.PutParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("callback_id", CallbackId);
            writer.WriteStringValue("category_id", CategoryId);
            writer.WriteStringValue("category_label", CategoryLabel);
            writer.WriteDoubleValue("date_created", DateCreated);
            writer.WriteDoubleValue("date_deleted", DateDeleted);
            writer.WriteDoubleValue("date_released", DateReleased);
            writer.WriteDoubleValue("date_updated", DateUpdated);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.FunctionFormEnabled>("form_enabled", FormEnabled);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.PutParameter>("input_parameters", InputParameters);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.PutParameter>("output_parameters", OutputParameters);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
