// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The type of block. For an input block, `type` is always `input`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InputBlockType
    {
        [EnumMember(Value = "input")]
        #pragma warning disable CS1591
        Input,
        #pragma warning restore CS1591
    }
}
