// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListRecordElement6 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public double? DateCreated { get; set; }
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField6>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField6> Fields { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_subscribed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6IsSubscribed? IsSubscribed { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6IsSubscribed IsSubscribed { get; set; }
#endif
        /// <summary>The list_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListId { get; set; }
#nullable restore
#else
        public string ListId { get; set; }
#endif
        /// <summary>The platform_refs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.PlatformRefs? PlatformRefs { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.PlatformRefs PlatformRefs { get; set; }
#endif
        /// <summary>The position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Position { get; set; }
#nullable restore
#else
        public string Position { get; set; }
#endif
        /// <summary>The saved property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Saved? Saved { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Saved Saved { get; set; }
#endif
        /// <summary>The thread_ts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreadTs { get; set; }
#nullable restore
#else
        public string ThreadTs { get; set; }
#endif
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The updated_timestamp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedTimestamp { get; set; }
#nullable restore
#else
        public string UpdatedTimestamp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6"/> and sets the default values.
        /// </summary>
        public ListRecordElement6()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDoubleValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField6>(global::Soenneker.Slack.OpenApiClient.Models.RecordField6.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_subscribed", n => { IsSubscribed = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6IsSubscribed>(global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6IsSubscribed.CreateFromDiscriminatorValue); } },
                { "list_id", n => { ListId = n.GetStringValue(); } },
                { "platform_refs", n => { PlatformRefs = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlatformRefs>(global::Soenneker.Slack.OpenApiClient.Models.PlatformRefs.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetStringValue(); } },
                { "saved", n => { Saved = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Saved>(global::Soenneker.Slack.OpenApiClient.Models.Saved.CreateFromDiscriminatorValue); } },
                { "thread_ts", n => { ThreadTs = n.GetStringValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetStringValue(); } },
                { "updated_timestamp", n => { UpdatedTimestamp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteDoubleValue("date_created", DateCreated);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField6>("fields", Fields);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ListRecordElement6IsSubscribed>("is_subscribed", IsSubscribed);
            writer.WriteStringValue("list_id", ListId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.PlatformRefs>("platform_refs", PlatformRefs);
            writer.WriteStringValue("position", Position);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Saved>("saved", Saved);
            writer.WriteStringValue("thread_ts", ThreadTs);
            writer.WriteStringValue("updated_by", UpdatedBy);
            writer.WriteStringValue("updated_timestamp", UpdatedTimestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
