// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagesMatchNoReactions : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper? MessagesMatchNoReactionsWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper MessagesMatchNoReactionsWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper2? MessagesMatchNoReactionsWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper2 MessagesMatchNoReactionsWrapper2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactions();
            result.MessagesMatchNoReactionsWrapper = new global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper();
            result.MessagesMatchNoReactionsWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MessagesMatchNoReactionsWrapper != null || MessagesMatchNoReactionsWrapper2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MessagesMatchNoReactionsWrapper, MessagesMatchNoReactionsWrapper2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MessagesMatchNoReactionsWrapper>(null, MessagesMatchNoReactionsWrapper, MessagesMatchNoReactionsWrapper2);
        }
    }
}
#pragma warning restore CS0618
