// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessageFileCanvasPrintingEnabled : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper? MessageFileCanvasPrintingEnabledWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper MessageFileCanvasPrintingEnabledWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper2? MessageFileCanvasPrintingEnabledWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper2 MessageFileCanvasPrintingEnabledWrapper2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabled"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabled CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabled();
            result.MessageFileCanvasPrintingEnabledWrapper = new global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper();
            result.MessageFileCanvasPrintingEnabledWrapper2 = new global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MessageFileCanvasPrintingEnabledWrapper != null || MessageFileCanvasPrintingEnabledWrapper2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MessageFileCanvasPrintingEnabledWrapper, MessageFileCanvasPrintingEnabledWrapper2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MessageFileCanvasPrintingEnabledWrapper>(null, MessageFileCanvasPrintingEnabledWrapper, MessageFileCanvasPrintingEnabledWrapper2);
        }
    }
}
#pragma warning restore CS0618
