// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MigrationExchangeResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enterprise_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnterpriseId { get; set; }
#nullable restore
#else
        public string EnterpriseId { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The invalid_user_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? InvalidUserIds { get; set; }
#nullable restore
#else
        public List<string> InvalidUserIds { get; set; }
#endif
        /// <summary>The needed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Needed { get; set; }
#nullable restore
#else
        public string Needed { get; set; }
#endif
        /// <summary>The ok property</summary>
        public bool? Ok { get; set; }
        /// <summary>The provided property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provided { get; set; }
#nullable restore
#else
        public string Provided { get; set; }
#endif
        /// <summary>The response_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata? ResponseMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata ResponseMetadata { get; set; }
#endif
        /// <summary>The team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The user_id_map property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponseUserIdMap? UserIdMap { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponseUserIdMap UserIdMap { get; set; }
#endif
        /// <summary>The warning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Warning { get; set; }
#nullable restore
#else
        public string Warning { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponse"/> and sets the default values.
        /// </summary>
        public MigrationExchangeResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enterprise_id", n => { EnterpriseId = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "invalid_user_ids", n => { InvalidUserIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "needed", n => { Needed = n.GetStringValue(); } },
                { "ok", n => { Ok = n.GetBoolValue(); } },
                { "provided", n => { Provided = n.GetStringValue(); } },
                { "response_metadata", n => { ResponseMetadata = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>(global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata.CreateFromDiscriminatorValue); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "user_id_map", n => { UserIdMap = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponseUserIdMap>(global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponseUserIdMap.CreateFromDiscriminatorValue); } },
                { "warning", n => { Warning = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("enterprise_id", EnterpriseId);
            writer.WriteStringValue("error", Error);
            writer.WriteCollectionOfPrimitiveValues<string>("invalid_user_ids", InvalidUserIds);
            writer.WriteStringValue("needed", Needed);
            writer.WriteBoolValue("ok", Ok);
            writer.WriteStringValue("provided", Provided);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WebApiCallResultResponseMetadata>("response_metadata", ResponseMetadata);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MigrationExchangeResponseUserIdMap>("user_id_map", UserIdMap);
            writer.WriteStringValue("warning", Warning);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
