// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// A filter object that reduces the list of available conversations using the specified criteria.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MultiConversationsSelectFilter : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The exclude_bot_users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeBotUsers? ExcludeBotUsers { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeBotUsers ExcludeBotUsers { get; set; }
#endif
        /// <summary>The exclude_external_shared_channels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeExternalSharedChannels? ExcludeExternalSharedChannels { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeExternalSharedChannels ExcludeExternalSharedChannels { get; set; }
#endif
        /// <summary>The include property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterIncludeItem?>? Include { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterIncludeItem?> Include { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilter"/> and sets the default values.
        /// </summary>
        public MultiConversationsSelectFilter()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "exclude_bot_users", n => { ExcludeBotUsers = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeBotUsers>(global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeBotUsers.CreateFromDiscriminatorValue); } },
                { "exclude_external_shared_channels", n => { ExcludeExternalSharedChannels = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeExternalSharedChannels>(global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeExternalSharedChannels.CreateFromDiscriminatorValue); } },
                { "include", n => { Include = n.GetCollectionOfEnumValues<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterIncludeItem>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeBotUsers>("exclude_bot_users", ExcludeBotUsers);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterExcludeExternalSharedChannels>("exclude_external_shared_channels", ExcludeExternalSharedChannels);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Slack.OpenApiClient.Models.MultiConversationsSelectFilterIncludeItem>("include", Include);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
