// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The type of element. In this case `type` is always `plain_text_input`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlainTextInputType
    {
        [EnumMember(Value = "plain_text_input")]
        #pragma warning disable CS1591
        PlainTextInput,
        #pragma warning restore CS1591
    }
}
