// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Profile4 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The always_active property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Profile4AlwaysActive? AlwaysActive { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Profile4AlwaysActive AlwaysActive { get; set; }
#endif
        /// <summary>The api_app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiAppId { get; set; }
#nullable restore
#else
        public string ApiAppId { get; set; }
#endif
        /// <summary>The avatar_hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarHash { get; set; }
#nullable restore
#else
        public string AvatarHash { get; set; }
#endif
        /// <summary>The bot_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BotId { get; set; }
#nullable restore
#else
        public string BotId { get; set; }
#endif
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The display_name_normalized property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayNameNormalized { get; set; }
#nullable restore
#else
        public string DisplayNameNormalized { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The guest_invited_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuestInvitedBy { get; set; }
#nullable restore
#else
        public string GuestInvitedBy { get; set; }
#endif
        /// <summary>The huddle_state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HuddleState { get; set; }
#nullable restore
#else
        public string HuddleState { get; set; }
#endif
        /// <summary>The huddle_state_expiration_ts property</summary>
        public double? HuddleStateExpirationTs { get; set; }
        /// <summary>The image_1024 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image1024 { get; set; }
#nullable restore
#else
        public string Image1024 { get; set; }
#endif
        /// <summary>The image_192 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image192 { get; set; }
#nullable restore
#else
        public string Image192 { get; set; }
#endif
        /// <summary>The image_24 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image24 { get; set; }
#nullable restore
#else
        public string Image24 { get; set; }
#endif
        /// <summary>The image_32 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image32 { get; set; }
#nullable restore
#else
        public string Image32 { get; set; }
#endif
        /// <summary>The image_48 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image48 { get; set; }
#nullable restore
#else
        public string Image48 { get; set; }
#endif
        /// <summary>The image_512 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image512 { get; set; }
#nullable restore
#else
        public string Image512 { get; set; }
#endif
        /// <summary>The image_72 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image72 { get; set; }
#nullable restore
#else
        public string Image72 { get; set; }
#endif
        /// <summary>The image_original property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageOriginal { get; set; }
#nullable restore
#else
        public string ImageOriginal { get; set; }
#endif
        /// <summary>The is_custom_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Profile4IsCustomImage? IsCustomImage { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Profile4IsCustomImage IsCustomImage { get; set; }
#endif
        /// <summary>The last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The pronouns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pronouns { get; set; }
#nullable restore
#else
        public string Pronouns { get; set; }
#endif
        /// <summary>The real_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RealName { get; set; }
#nullable restore
#else
        public string RealName { get; set; }
#endif
        /// <summary>The real_name_normalized property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RealNameNormalized { get; set; }
#nullable restore
#else
        public string RealNameNormalized { get; set; }
#endif
        /// <summary>The skype property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Skype { get; set; }
#nullable restore
#else
        public string Skype { get; set; }
#endif
        /// <summary>The status_emoji property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusEmoji { get; set; }
#nullable restore
#else
        public string StatusEmoji { get; set; }
#endif
        /// <summary>The status_emoji_display_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.StatusEmojiDisplayInfo>? StatusEmojiDisplayInfo { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.StatusEmojiDisplayInfo> StatusEmojiDisplayInfo { get; set; }
#endif
        /// <summary>The status_emoji_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusEmojiUrl { get; set; }
#nullable restore
#else
        public string StatusEmojiUrl { get; set; }
#endif
        /// <summary>The status_expiration property</summary>
        public double? StatusExpiration { get; set; }
        /// <summary>The status_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusText { get; set; }
#nullable restore
#else
        public string StatusText { get; set; }
#endif
        /// <summary>The status_text_canonical property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusTextCanonical { get; set; }
#nullable restore
#else
        public string StatusTextCanonical { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Team { get; set; }
#nullable restore
#else
        public string Team { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Profile4"/> and sets the default values.
        /// </summary>
        public Profile4()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Profile4"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Profile4 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Profile4();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "always_active", n => { AlwaysActive = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Profile4AlwaysActive>(global::Soenneker.Slack.OpenApiClient.Models.Profile4AlwaysActive.CreateFromDiscriminatorValue); } },
                { "api_app_id", n => { ApiAppId = n.GetStringValue(); } },
                { "avatar_hash", n => { AvatarHash = n.GetStringValue(); } },
                { "bot_id", n => { BotId = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "display_name_normalized", n => { DisplayNameNormalized = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "guest_invited_by", n => { GuestInvitedBy = n.GetStringValue(); } },
                { "huddle_state", n => { HuddleState = n.GetStringValue(); } },
                { "huddle_state_expiration_ts", n => { HuddleStateExpirationTs = n.GetDoubleValue(); } },
                { "image_1024", n => { Image1024 = n.GetStringValue(); } },
                { "image_192", n => { Image192 = n.GetStringValue(); } },
                { "image_24", n => { Image24 = n.GetStringValue(); } },
                { "image_32", n => { Image32 = n.GetStringValue(); } },
                { "image_48", n => { Image48 = n.GetStringValue(); } },
                { "image_512", n => { Image512 = n.GetStringValue(); } },
                { "image_72", n => { Image72 = n.GetStringValue(); } },
                { "image_original", n => { ImageOriginal = n.GetStringValue(); } },
                { "is_custom_image", n => { IsCustomImage = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Profile4IsCustomImage>(global::Soenneker.Slack.OpenApiClient.Models.Profile4IsCustomImage.CreateFromDiscriminatorValue); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "pronouns", n => { Pronouns = n.GetStringValue(); } },
                { "real_name", n => { RealName = n.GetStringValue(); } },
                { "real_name_normalized", n => { RealNameNormalized = n.GetStringValue(); } },
                { "skype", n => { Skype = n.GetStringValue(); } },
                { "status_emoji", n => { StatusEmoji = n.GetStringValue(); } },
                { "status_emoji_display_info", n => { StatusEmojiDisplayInfo = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.StatusEmojiDisplayInfo>(global::Soenneker.Slack.OpenApiClient.Models.StatusEmojiDisplayInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status_emoji_url", n => { StatusEmojiUrl = n.GetStringValue(); } },
                { "status_expiration", n => { StatusExpiration = n.GetDoubleValue(); } },
                { "status_text", n => { StatusText = n.GetStringValue(); } },
                { "status_text_canonical", n => { StatusTextCanonical = n.GetStringValue(); } },
                { "team", n => { Team = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Profile4AlwaysActive>("always_active", AlwaysActive);
            writer.WriteStringValue("api_app_id", ApiAppId);
            writer.WriteStringValue("avatar_hash", AvatarHash);
            writer.WriteStringValue("bot_id", BotId);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteStringValue("display_name_normalized", DisplayNameNormalized);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteStringValue("guest_invited_by", GuestInvitedBy);
            writer.WriteStringValue("huddle_state", HuddleState);
            writer.WriteDoubleValue("huddle_state_expiration_ts", HuddleStateExpirationTs);
            writer.WriteStringValue("image_1024", Image1024);
            writer.WriteStringValue("image_192", Image192);
            writer.WriteStringValue("image_24", Image24);
            writer.WriteStringValue("image_32", Image32);
            writer.WriteStringValue("image_48", Image48);
            writer.WriteStringValue("image_512", Image512);
            writer.WriteStringValue("image_72", Image72);
            writer.WriteStringValue("image_original", ImageOriginal);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Profile4IsCustomImage>("is_custom_image", IsCustomImage);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("pronouns", Pronouns);
            writer.WriteStringValue("real_name", RealName);
            writer.WriteStringValue("real_name_normalized", RealNameNormalized);
            writer.WriteStringValue("skype", Skype);
            writer.WriteStringValue("status_emoji", StatusEmoji);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.StatusEmojiDisplayInfo>("status_emoji_display_info", StatusEmojiDisplayInfo);
            writer.WriteStringValue("status_emoji_url", StatusEmojiUrl);
            writer.WriteDoubleValue("status_expiration", StatusExpiration);
            writer.WriteStringValue("status_text", StatusText);
            writer.WriteStringValue("status_text_canonical", StatusTextCanonical);
            writer.WriteStringValue("team", Team);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
