// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Properties5 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The canvas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Canvas? Canvas { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Canvas Canvas { get; set; }
#endif
        /// <summary>The channel_workflows property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.ChannelWorkflow>? ChannelWorkflows { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.ChannelWorkflow> ChannelWorkflows { get; set; }
#endif
        /// <summary>The has_slack_connect_invite_created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Properties5HasSlackConnectInviteCreated? HasSlackConnectInviteCreated { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Properties5HasSlackConnectInviteCreated HasSlackConnectInviteCreated { get; set; }
#endif
        /// <summary>The is_dormant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Properties5IsDormant? IsDormant { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Properties5IsDormant IsDormant { get; set; }
#endif
        /// <summary>The meeting_notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.MeetingNotes? MeetingNotes { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.MeetingNotes MeetingNotes { get; set; }
#endif
        /// <summary>The posting_restricted_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2? PostingRestrictedTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2 PostingRestrictedTo { get; set; }
#endif
        /// <summary>The tabs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Tab4>? Tabs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Tab4> Tabs { get; set; }
#endif
        /// <summary>The tabz property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Tab4>? Tabz { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Tab4> Tabz { get; set; }
#endif
        /// <summary>The threads_restricted_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2? ThreadsRestrictedTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2 ThreadsRestrictedTo { get; set; }
#endif
        /// <summary>The use_case property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseCase { get; set; }
#nullable restore
#else
        public string UseCase { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Properties5"/> and sets the default values.
        /// </summary>
        public Properties5()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Properties5"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Properties5 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Properties5();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canvas", n => { Canvas = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Canvas>(global::Soenneker.Slack.OpenApiClient.Models.Canvas.CreateFromDiscriminatorValue); } },
                { "channel_workflows", n => { ChannelWorkflows = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.ChannelWorkflow>(global::Soenneker.Slack.OpenApiClient.Models.ChannelWorkflow.CreateFromDiscriminatorValue)?.AsList(); } },
                { "has_slack_connect_invite_created", n => { HasSlackConnectInviteCreated = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Properties5HasSlackConnectInviteCreated>(global::Soenneker.Slack.OpenApiClient.Models.Properties5HasSlackConnectInviteCreated.CreateFromDiscriminatorValue); } },
                { "is_dormant", n => { IsDormant = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Properties5IsDormant>(global::Soenneker.Slack.OpenApiClient.Models.Properties5IsDormant.CreateFromDiscriminatorValue); } },
                { "meeting_notes", n => { MeetingNotes = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MeetingNotes>(global::Soenneker.Slack.OpenApiClient.Models.MeetingNotes.CreateFromDiscriminatorValue); } },
                { "posting_restricted_to", n => { PostingRestrictedTo = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2>(global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2.CreateFromDiscriminatorValue); } },
                { "tabs", n => { Tabs = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Tab4>(global::Soenneker.Slack.OpenApiClient.Models.Tab4.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tabz", n => { Tabz = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Tab4>(global::Soenneker.Slack.OpenApiClient.Models.Tab4.CreateFromDiscriminatorValue)?.AsList(); } },
                { "threads_restricted_to", n => { ThreadsRestrictedTo = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2>(global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2.CreateFromDiscriminatorValue); } },
                { "use_case", n => { UseCase = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Canvas>("canvas", Canvas);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.ChannelWorkflow>("channel_workflows", ChannelWorkflows);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Properties5HasSlackConnectInviteCreated>("has_slack_connect_invite_created", HasSlackConnectInviteCreated);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Properties5IsDormant>("is_dormant", IsDormant);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.MeetingNotes>("meeting_notes", MeetingNotes);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2>("posting_restricted_to", PostingRestrictedTo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Tab4>("tabs", Tabs);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Tab4>("tabz", Tabz);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RestrictedTo2>("threads_restricted_to", ThreadsRestrictedTo);
            writer.WriteStringValue("use_case", UseCase);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
