// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecordField4 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4AttachmentItem>? Attachment { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4AttachmentItem> Attachment { get; set; }
#endif
        /// <summary>The channel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4ChannelItem>? Channel { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4ChannelItem> Channel { get; set; }
#endif
        /// <summary>The checkbox property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RecordField4Checkbox? Checkbox { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RecordField4Checkbox Checkbox { get; set; }
#endif
        /// <summary>The column_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColumnId { get; set; }
#nullable restore
#else
        public string ColumnId { get; set; }
#endif
        /// <summary>The date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4DateItem>? Date { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4DateItem> Date { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4EmailItem>? Email { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4EmailItem> Email { get; set; }
#endif
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.FieldMessage4? Message { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.FieldMessage4 Message { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4NumberItem>? Number { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4NumberItem> Number { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4PhoneItem>? Phone { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4PhoneItem> Phone { get; set; }
#endif
        /// <summary>The rating property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RatingItem>? Rating { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RatingItem> Rating { get; set; }
#endif
        /// <summary>The rich_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RichTextItem>? RichText { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RichTextItem> RichText { get; set; }
#endif
        /// <summary>The select property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4SelectItem>? Select { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4SelectItem> Select { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The timestamp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4TimestampItem>? Timestamp { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4TimestampItem> Timestamp { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4UserItem>? User { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RecordField4UserItem> User { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.RecordField4"/> and sets the default values.
        /// </summary>
        public RecordField4()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.RecordField4"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.RecordField4 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.RecordField4();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachment", n => { Attachment = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4AttachmentItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4AttachmentItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "channel", n => { Channel = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4ChannelItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4ChannelItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "checkbox", n => { Checkbox = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RecordField4Checkbox>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4Checkbox.CreateFromDiscriminatorValue); } },
                { "column_id", n => { ColumnId = n.GetStringValue(); } },
                { "date", n => { Date = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4DateItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4DateItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "email", n => { Email = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4EmailItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4EmailItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "message", n => { Message = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.FieldMessage4>(global::Soenneker.Slack.OpenApiClient.Models.FieldMessage4.CreateFromDiscriminatorValue); } },
                { "number", n => { Number = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4NumberItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4NumberItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "phone", n => { Phone = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4PhoneItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4PhoneItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rating", n => { Rating = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RatingItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4RatingItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rich_text", n => { RichText = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RichTextItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4RichTextItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "select", n => { Select = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4SelectItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4SelectItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4TimestampItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4TimestampItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "user", n => { User = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4UserItem>(global::Soenneker.Slack.OpenApiClient.Models.RecordField4UserItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4AttachmentItem>("attachment", Attachment);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4ChannelItem>("channel", Channel);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RecordField4Checkbox>("checkbox", Checkbox);
            writer.WriteStringValue("column_id", ColumnId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4DateItem>("date", Date);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4EmailItem>("email", Email);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.FieldMessage4>("message", Message);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4NumberItem>("number", Number);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4PhoneItem>("phone", Phone);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RatingItem>("rating", Rating);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4RichTextItem>("rich_text", RichText);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4SelectItem>("select", Select);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4TimestampItem>("timestamp", Timestamp);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RecordField4UserItem>("user", User);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
