// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The range of the broadcast; can be one of `here`, `channel` and `everyone`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RichTextBroadcastMentionRange
    {
        [EnumMember(Value = "everyone")]
        #pragma warning disable CS1591
        Everyone,
        #pragma warning restore CS1591
        [EnumMember(Value = "here")]
        #pragma warning disable CS1591
        Here,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel")]
        #pragma warning disable CS1591
        Channel,
        #pragma warning restore CS1591
    }
}
