// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// A limited style object for styling rich text `text` elements.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RichTextColorStyle : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When `true`, boldens the text in this element. Defaults to `false`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleBold? Bold { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleBold Bold { get; set; }
#endif
        /// <summary>When `true`, the text is preformatted in an inline code style. Defaults to `false.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleCode? Code { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleCode Code { get; set; }
#endif
        /// <summary>When `true`, italicizes the text in this element. Defaults to `false`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleItalic? Italic { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleItalic Italic { get; set; }
#endif
        /// <summary>When `true`, strikes through the text in this element. Defaults to `false`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleStrike? Strike { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleStrike Strike { get; set; }
#endif
        /// <summary>When `true`, underlines the text in this element. Defaults to `false`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleUnderline? Underline { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleUnderline Underline { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyle"/> and sets the default values.
        /// </summary>
        public RichTextColorStyle()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyle"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyle CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyle();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bold", n => { Bold = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleBold>(global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleBold.CreateFromDiscriminatorValue); } },
                { "code", n => { Code = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleCode>(global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleCode.CreateFromDiscriminatorValue); } },
                { "italic", n => { Italic = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleItalic>(global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleItalic.CreateFromDiscriminatorValue); } },
                { "strike", n => { Strike = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleStrike>(global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleStrike.CreateFromDiscriminatorValue); } },
                { "underline", n => { Underline = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleUnderline>(global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleUnderline.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleBold>("bold", Bold);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleCode>("code", Code);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleItalic>("italic", Italic);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleStrike>("strike", Strike);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextColorStyleUnderline>("underline", Underline);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
