// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RichTextSection2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "rich_text_section")]
        #pragma warning disable CS1591
        RichTextSection,
        #pragma warning restore CS1591
    }
}
