// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RichTextList : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to render a quote-block-like border on the inline side of the list. `0` renders no borderwhile `1` renders a border.</summary>
        public double? Border { get; set; }
        /// <summary>An array of [RichTextSection](RichTextSection) elements comprising each list item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.RichTextSection>? Elements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.RichTextSection> Elements { get; set; }
#endif
        /// <summary>The style of the list points. Can be a number from `0` (default) to `8`. Yields a different characteror characters rendered as the list points. Also affected by the `style` property.</summary>
        public double? Indent { get; set; }
        /// <summary>The type of list. Can be either `bullet` (the list points are all rendered the same way) or `ordered`(the list points increase numerically from 1).</summary>
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextListStyle? Style { get; set; }
        /// <summary>The type of element. In this case `type` is always `rich_text_list`.</summary>
        public global::Soenneker.Slack.OpenApiClient.Models.RichTextListType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextList"/> and sets the default values.
        /// </summary>
        public RichTextList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.RichTextList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.RichTextList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.RichTextList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "border", n => { Border = n.GetDoubleValue(); } },
                { "elements", n => { Elements = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RichTextSection>(global::Soenneker.Slack.OpenApiClient.Models.RichTextSection.CreateFromDiscriminatorValue)?.AsList(); } },
                { "indent", n => { Indent = n.GetDoubleValue(); } },
                { "style", n => { Style = n.GetEnumValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextListStyle>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextListType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("border", Border);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.RichTextSection>("elements", Elements);
            writer.WriteDoubleValue("indent", Indent);
            writer.WriteEnumValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextListStyle>("style", Style);
            writer.WriteEnumValue<global::Soenneker.Slack.OpenApiClient.Models.RichTextListType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
