// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>The type of element. In this case `type` is always `team`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RichTextTeamMentionType
    {
        [EnumMember(Value = "team")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
    }
}
