// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Room2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The attached_file_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2AttachedFileIdsItem>? AttachedFileIds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2AttachedFileIdsItem> AttachedFileIds { get; set; }
#endif
        /// <summary>The background_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundId { get; set; }
#nullable restore
#else
        public string BackgroundId { get; set; }
#endif
        /// <summary>The call_family property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallFamily { get; set; }
#nullable restore
#else
        public string CallFamily { get; set; }
#endif
        /// <summary>The canvas_background property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanvasBackground { get; set; }
#nullable restore
#else
        public string CanvasBackground { get; set; }
#endif
        /// <summary>The canvas_thread_ts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanvasThreadTs { get; set; }
#nullable restore
#else
        public string CanvasThreadTs { get; set; }
#endif
        /// <summary>The channels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ChannelsItem>? Channels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ChannelsItem> Channels { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The date_end property</summary>
        public double? DateEnd { get; set; }
        /// <summary>The date_start property</summary>
        public double? DateStart { get; set; }
        /// <summary>The display_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayId { get; set; }
#nullable restore
#else
        public string DisplayId { get; set; }
#endif
        /// <summary>The external_unique_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalUniqueId { get; set; }
#nullable restore
#else
        public string ExternalUniqueId { get; set; }
#endif
        /// <summary>The has_ended property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2HasEnded? HasEnded { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2HasEnded HasEnded { get; set; }
#endif
        /// <summary>The huddle_link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HuddleLink { get; set; }
#nullable restore
#else
        public string HuddleLink { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_dm_call property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2IsDmCall? IsDmCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2IsDmCall IsDmCall { get; set; }
#endif
        /// <summary>The is_prewarmed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2IsPrewarmed? IsPrewarmed { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2IsPrewarmed IsPrewarmed { get; set; }
#endif
        /// <summary>The is_scheduled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2IsScheduled? IsScheduled { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2IsScheduled IsScheduled { get; set; }
#endif
        /// <summary>The media_backend_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaBackendType { get; set; }
#nullable restore
#else
        public string MediaBackendType { get; set; }
#endif
        /// <summary>The media_server property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaServer { get; set; }
#nullable restore
#else
        public string MediaServer { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The participant_history property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantHistoryItem>? ParticipantHistory { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantHistoryItem> ParticipantHistory { get; set; }
#endif
        /// <summary>The participants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsItem>? Participants { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsItem> Participants { get; set; }
#endif
        /// <summary>The participants_camera_off property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOffItem>? ParticipantsCameraOff { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOffItem> ParticipantsCameraOff { get; set; }
#endif
        /// <summary>The participants_camera_on property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOnItem>? ParticipantsCameraOn { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOnItem> ParticipantsCameraOn { get; set; }
#endif
        /// <summary>The participants_screenshare_off property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOffItem>? ParticipantsScreenshareOff { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOffItem> ParticipantsScreenshareOff { get; set; }
#endif
        /// <summary>The participants_screenshare_on property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOnItem>? ParticipantsScreenshareOn { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOnItem> ParticipantsScreenshareOn { get; set; }
#endif
        /// <summary>The recording property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Recording? Recording { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Recording Recording { get; set; }
#endif
        /// <summary>The thread_root_ts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreadRootTs { get; set; }
#nullable restore
#else
        public string ThreadRootTs { get; set; }
#endif
        /// <summary>The was_accepted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2WasAccepted? WasAccepted { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2WasAccepted WasAccepted { get; set; }
#endif
        /// <summary>The was_missed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2WasMissed? WasMissed { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2WasMissed WasMissed { get; set; }
#endif
        /// <summary>The was_rejected property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Room2WasRejected? WasRejected { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Room2WasRejected WasRejected { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Room2"/> and sets the default values.
        /// </summary>
        public Room2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Room2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Room2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Room2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "attached_file_ids", n => { AttachedFileIds = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2AttachedFileIdsItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2AttachedFileIdsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "background_id", n => { BackgroundId = n.GetStringValue(); } },
                { "call_family", n => { CallFamily = n.GetStringValue(); } },
                { "canvas_background", n => { CanvasBackground = n.GetStringValue(); } },
                { "canvas_thread_ts", n => { CanvasThreadTs = n.GetStringValue(); } },
                { "channels", n => { Channels = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ChannelsItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ChannelsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "date_end", n => { DateEnd = n.GetDoubleValue(); } },
                { "date_start", n => { DateStart = n.GetDoubleValue(); } },
                { "display_id", n => { DisplayId = n.GetStringValue(); } },
                { "external_unique_id", n => { ExternalUniqueId = n.GetStringValue(); } },
                { "has_ended", n => { HasEnded = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2HasEnded>(global::Soenneker.Slack.OpenApiClient.Models.Room2HasEnded.CreateFromDiscriminatorValue); } },
                { "huddle_link", n => { HuddleLink = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_dm_call", n => { IsDmCall = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2IsDmCall>(global::Soenneker.Slack.OpenApiClient.Models.Room2IsDmCall.CreateFromDiscriminatorValue); } },
                { "is_prewarmed", n => { IsPrewarmed = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2IsPrewarmed>(global::Soenneker.Slack.OpenApiClient.Models.Room2IsPrewarmed.CreateFromDiscriminatorValue); } },
                { "is_scheduled", n => { IsScheduled = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2IsScheduled>(global::Soenneker.Slack.OpenApiClient.Models.Room2IsScheduled.CreateFromDiscriminatorValue); } },
                { "media_backend_type", n => { MediaBackendType = n.GetStringValue(); } },
                { "media_server", n => { MediaServer = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "participant_history", n => { ParticipantHistory = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantHistoryItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantHistoryItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "participants", n => { Participants = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "participants_camera_off", n => { ParticipantsCameraOff = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOffItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOffItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "participants_camera_on", n => { ParticipantsCameraOn = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOnItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOnItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "participants_screenshare_off", n => { ParticipantsScreenshareOff = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOffItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOffItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "participants_screenshare_on", n => { ParticipantsScreenshareOn = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOnItem>(global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOnItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recording", n => { Recording = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Recording>(global::Soenneker.Slack.OpenApiClient.Models.Recording.CreateFromDiscriminatorValue); } },
                { "thread_root_ts", n => { ThreadRootTs = n.GetStringValue(); } },
                { "was_accepted", n => { WasAccepted = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2WasAccepted>(global::Soenneker.Slack.OpenApiClient.Models.Room2WasAccepted.CreateFromDiscriminatorValue); } },
                { "was_missed", n => { WasMissed = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2WasMissed>(global::Soenneker.Slack.OpenApiClient.Models.Room2WasMissed.CreateFromDiscriminatorValue); } },
                { "was_rejected", n => { WasRejected = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2WasRejected>(global::Soenneker.Slack.OpenApiClient.Models.Room2WasRejected.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_id", AppId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2AttachedFileIdsItem>("attached_file_ids", AttachedFileIds);
            writer.WriteStringValue("background_id", BackgroundId);
            writer.WriteStringValue("call_family", CallFamily);
            writer.WriteStringValue("canvas_background", CanvasBackground);
            writer.WriteStringValue("canvas_thread_ts", CanvasThreadTs);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ChannelsItem>("channels", Channels);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteDoubleValue("date_end", DateEnd);
            writer.WriteDoubleValue("date_start", DateStart);
            writer.WriteStringValue("display_id", DisplayId);
            writer.WriteStringValue("external_unique_id", ExternalUniqueId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2HasEnded>("has_ended", HasEnded);
            writer.WriteStringValue("huddle_link", HuddleLink);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2IsDmCall>("is_dm_call", IsDmCall);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2IsPrewarmed>("is_prewarmed", IsPrewarmed);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2IsScheduled>("is_scheduled", IsScheduled);
            writer.WriteStringValue("media_backend_type", MediaBackendType);
            writer.WriteStringValue("media_server", MediaServer);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantHistoryItem>("participant_history", ParticipantHistory);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsItem>("participants", Participants);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOffItem>("participants_camera_off", ParticipantsCameraOff);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsCameraOnItem>("participants_camera_on", ParticipantsCameraOn);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOffItem>("participants_screenshare_off", ParticipantsScreenshareOff);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Room2ParticipantsScreenshareOnItem>("participants_screenshare_on", ParticipantsScreenshareOn);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Recording>("recording", Recording);
            writer.WriteStringValue("thread_root_ts", ThreadRootTs);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2WasAccepted>("was_accepted", WasAccepted);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2WasMissed>("was_missed", WasMissed);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Room2WasRejected>("was_rejected", WasRejected);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
