// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>Return matches sorted by either `score` or `timestamp`. Defaults to `score`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchAllArgumentsSort
    {
        [EnumMember(Value = "score")]
        #pragma warning disable CS1591
        Score,
        #pragma warning restore CS1591
        [EnumMember(Value = "timestamp")]
        #pragma warning disable CS1591
        Timestamp,
        #pragma warning restore CS1591
    }
}
