// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>Name of the parameter that we are sorting by. Defaults to `team_name`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamExternalTeamsListArgumentsSortField
    {
        [EnumMember(Value = "team_name")]
        #pragma warning disable CS1591
        TeamName,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_active_timestamp")]
        #pragma warning disable CS1591
        LastActiveTimestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection_status")]
        #pragma warning disable CS1591
        ConnectionStatus,
        #pragma warning restore CS1591
    }
}
