// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Slack.OpenApiClient.Models.BroadcastWrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Channel2Wrapper3"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.ColorWrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.DateWrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Emoji2Wrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.LinkWrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Team5Wrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.TextWrapper4"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.User4Wrapper5"/>, <see cref="global::Soenneker.Slack.OpenApiClient.Models.Usergroup2Wrapper5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TentacledElementType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.BroadcastWrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.BroadcastWrapper5? BroadcastWrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.BroadcastWrapper5 BroadcastWrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Channel2Wrapper3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Channel2Wrapper3? Channel2Wrapper3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Channel2Wrapper3 Channel2Wrapper3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.ColorWrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ColorWrapper5? ColorWrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ColorWrapper5 ColorWrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.DateWrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.DateWrapper5? DateWrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.DateWrapper5 DateWrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Emoji2Wrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Emoji2Wrapper5? Emoji2Wrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Emoji2Wrapper5 Emoji2Wrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.LinkWrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.LinkWrapper5? LinkWrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.LinkWrapper5 LinkWrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Team5Wrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Team5Wrapper5? Team5Wrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Team5Wrapper5 Team5Wrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.TextWrapper4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.TextWrapper4? TextWrapper4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.TextWrapper4 TextWrapper4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.User4Wrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.User4Wrapper5? User4Wrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.User4Wrapper5 User4Wrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Slack.OpenApiClient.Models.Usergroup2Wrapper5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Usergroup2Wrapper5? Usergroup2Wrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Usergroup2Wrapper5 Usergroup2Wrapper5 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.TentacledElementType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.TentacledElementType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Slack.OpenApiClient.Models.TentacledElementType();
            result.BroadcastWrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.BroadcastWrapper5();
            result.Channel2Wrapper3 = new global::Soenneker.Slack.OpenApiClient.Models.Channel2Wrapper3();
            result.ColorWrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.ColorWrapper5();
            result.DateWrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.DateWrapper5();
            result.Emoji2Wrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.Emoji2Wrapper5();
            result.LinkWrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.LinkWrapper5();
            result.Team5Wrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.Team5Wrapper5();
            result.TextWrapper4 = new global::Soenneker.Slack.OpenApiClient.Models.TextWrapper4();
            result.User4Wrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.User4Wrapper5();
            result.Usergroup2Wrapper5 = new global::Soenneker.Slack.OpenApiClient.Models.Usergroup2Wrapper5();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BroadcastWrapper5 != null || Channel2Wrapper3 != null || ColorWrapper5 != null || DateWrapper5 != null || Emoji2Wrapper5 != null || LinkWrapper5 != null || Team5Wrapper5 != null || TextWrapper4 != null || User4Wrapper5 != null || Usergroup2Wrapper5 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BroadcastWrapper5, Channel2Wrapper3, ColorWrapper5, DateWrapper5, Emoji2Wrapper5, LinkWrapper5, Team5Wrapper5, TextWrapper4, User4Wrapper5, Usergroup2Wrapper5);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.BroadcastWrapper5>(null, BroadcastWrapper5, Channel2Wrapper3, ColorWrapper5, DateWrapper5, Emoji2Wrapper5, LinkWrapper5, Team5Wrapper5, TextWrapper4, User4Wrapper5, Usergroup2Wrapper5);
        }
    }
}
#pragma warning restore CS0618
