// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsersConversationsArguments : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attributereturned by a previous request&apos;s `response_metadata`.Default value fetches the first &quot;page&quot; of the collection.[pagination](https://docs.slack.dev/apis/web-api/pagination) for more detail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>Set to `true` to exclude archived channels from the list. Default is `false`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArgumentsExcludeArchived? ExcludeArchived { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArgumentsExcludeArchived ExcludeArchived { get; set; }
#endif
        /// <summary>The maximum number of items to return. Fewer than the requested number of items may be returned,even if the end of the list hasn&apos;t been reached. Must be an integer with a max value of `999`. Default is `100`.</summary>
        public double? Limit { get; set; }
        /// <summary>If using an org token, `team_id` is required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>Overridable authentication token bearing required scopes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>Mix and match channel types by providing a comma-separated list of any combination of`public_channel`, `private_channel`, `mpim` and `im`. Defaults to `public_channel`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Types { get; set; }
#nullable restore
#else
        public string Types { get; set; }
#endif
        /// <summary>Browse conversations by a specific user ID&apos;s membership.Non-public channels are restricted to those where the calling user shares membership.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArguments"/> and sets the default values.
        /// </summary>
        public UsersConversationsArguments()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArguments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArguments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArguments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "exclude_archived", n => { ExcludeArchived = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArgumentsExcludeArchived>(global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArgumentsExcludeArchived.CreateFromDiscriminatorValue); } },
                { "limit", n => { Limit = n.GetDoubleValue(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "types", n => { Types = n.GetStringValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.UsersConversationsArgumentsExcludeArchived>("exclude_archived", ExcludeArchived);
            writer.WriteDoubleValue("limit", Limit);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteStringValue("token", Token);
            writer.WriteStringValue("types", Types);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
