// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ViewSubmitAction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The api_app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiAppId { get; set; }
#nullable restore
#else
        public string ApiAppId { get; set; }
#endif
        /// <summary>The enterprise property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionEnterprise? Enterprise { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionEnterprise Enterprise { get; set; }
#endif
        /// <summary>The is_enterprise_install property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionIsEnterpriseInstall? IsEnterpriseInstall { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionIsEnterpriseInstall IsEnterpriseInstall { get; set; }
#endif
        /// <summary>The response_urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.ViewResponseUrl>? ResponseUrls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.ViewResponseUrl> ResponseUrls { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionTeam? Team { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionTeam Team { get; set; }
#endif
        /// <summary>The token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>The trigger_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerId { get; set; }
#nullable restore
#else
        public string TriggerId { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmissionType? Type { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionUser User { get; set; }
#endif
        /// <summary>The view property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.ViewOutput? View { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.ViewOutput View { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitAction"/> and sets the default values.
        /// </summary>
        public ViewSubmitAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_app_id", n => { ApiAppId = n.GetStringValue(); } },
                { "enterprise", n => { Enterprise = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionEnterprise>(global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionEnterprise.CreateFromDiscriminatorValue); } },
                { "is_enterprise_install", n => { IsEnterpriseInstall = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionIsEnterpriseInstall>(global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionIsEnterpriseInstall.CreateFromDiscriminatorValue); } },
                { "response_urls", n => { ResponseUrls = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.ViewResponseUrl>(global::Soenneker.Slack.OpenApiClient.Models.ViewResponseUrl.CreateFromDiscriminatorValue)?.AsList(); } },
                { "team", n => { Team = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionTeam>(global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionTeam.CreateFromDiscriminatorValue); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "trigger_id", n => { TriggerId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmissionType>(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionUser>(global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionUser.CreateFromDiscriminatorValue); } },
                { "view", n => { View = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewOutput>(global::Soenneker.Slack.OpenApiClient.Models.ViewOutput.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_app_id", ApiAppId);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionEnterprise>("enterprise", Enterprise);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionIsEnterpriseInstall>("is_enterprise_install", IsEnterpriseInstall);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.ViewResponseUrl>("response_urls", ResponseUrls);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionTeam>("team", Team);
            writer.WriteStringValue("token", Token);
            writer.WriteStringValue("trigger_id", TriggerId);
            writer.WriteEnumValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmissionType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewSubmitActionUser>("user", User);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.ViewOutput>("view", View);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
