// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Slack.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Workflow : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The billing_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingType { get; set; }
#nullable restore
#else
        public string BillingType { get; set; }
#endif
        /// <summary>The callback_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackId { get; set; }
#nullable restore
#else
        public string CallbackId { get; set; }
#endif
        /// <summary>The collaborators property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Collaborators { get; set; }
#nullable restore
#else
        public List<string> Collaborators { get; set; }
#endif
        /// <summary>The date_updated property</summary>
        public double? DateUpdated { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The icons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.Icons3? Icons { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.Icons3 Icons { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The input_parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowInputParametersProperty? InputParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowInputParametersProperty InputParameters { get; set; }
#endif
        /// <summary>The is_billable property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsBillable? IsBillable { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsBillable IsBillable { get; set; }
#endif
        /// <summary>The is_published property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsPublished? IsPublished { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsPublished IsPublished { get; set; }
#endif
        /// <summary>The is_sales_home_workflow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsSalesHomeWorkflow? IsSalesHomeWorkflow { get; set; }
#nullable restore
#else
        public global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsSalesHomeWorkflow IsSalesHomeWorkflow { get; set; }
#endif
        /// <summary>The last_published_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPublishedDate { get; set; }
#nullable restore
#else
        public string LastPublishedDate { get; set; }
#endif
        /// <summary>The last_published_version_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPublishedVersionId { get; set; }
#nullable restore
#else
        public string LastPublishedVersionId { get; set; }
#endif
        /// <summary>The last_updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedBy { get; set; }
#nullable restore
#else
        public string LastUpdatedBy { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Slack.OpenApiClient.Models.Step>? Steps { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Slack.OpenApiClient.Models.Step> Steps { get; set; }
#endif
        /// <summary>The team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The trigger_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TriggerIds { get; set; }
#nullable restore
#else
        public List<string> TriggerIds { get; set; }
#endif
        /// <summary>The unpublished_change_count property</summary>
        public double? UnpublishedChangeCount { get; set; }
        /// <summary>The workflow_function_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowFunctionId { get; set; }
#nullable restore
#else
        public string WorkflowFunctionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Slack.OpenApiClient.Models.Workflow"/> and sets the default values.
        /// </summary>
        public Workflow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Slack.OpenApiClient.Models.Workflow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Slack.OpenApiClient.Models.Workflow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Slack.OpenApiClient.Models.Workflow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "billing_type", n => { BillingType = n.GetStringValue(); } },
                { "callback_id", n => { CallbackId = n.GetStringValue(); } },
                { "collaborators", n => { Collaborators = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "date_updated", n => { DateUpdated = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "icons", n => { Icons = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Icons3>(global::Soenneker.Slack.OpenApiClient.Models.Icons3.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input_parameters", n => { InputParameters = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowInputParametersProperty>(global::Soenneker.Slack.OpenApiClient.Models.WorkflowInputParametersProperty.CreateFromDiscriminatorValue); } },
                { "is_billable", n => { IsBillable = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsBillable>(global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsBillable.CreateFromDiscriminatorValue); } },
                { "is_published", n => { IsPublished = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsPublished>(global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsPublished.CreateFromDiscriminatorValue); } },
                { "is_sales_home_workflow", n => { IsSalesHomeWorkflow = n.GetObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsSalesHomeWorkflow>(global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsSalesHomeWorkflow.CreateFromDiscriminatorValue); } },
                { "last_published_date", n => { LastPublishedDate = n.GetStringValue(); } },
                { "last_published_version_id", n => { LastPublishedVersionId = n.GetStringValue(); } },
                { "last_updated_by", n => { LastUpdatedBy = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Step>(global::Soenneker.Slack.OpenApiClient.Models.Step.CreateFromDiscriminatorValue)?.AsList(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "trigger_ids", n => { TriggerIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "unpublished_change_count", n => { UnpublishedChangeCount = n.GetDoubleValue(); } },
                { "workflow_function_id", n => { WorkflowFunctionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("billing_type", BillingType);
            writer.WriteStringValue("callback_id", CallbackId);
            writer.WriteCollectionOfPrimitiveValues<string>("collaborators", Collaborators);
            writer.WriteDoubleValue("date_updated", DateUpdated);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.Icons3>("icons", Icons);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowInputParametersProperty>("input_parameters", InputParameters);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsBillable>("is_billable", IsBillable);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsPublished>("is_published", IsPublished);
            writer.WriteObjectValue<global::Soenneker.Slack.OpenApiClient.Models.WorkflowIsSalesHomeWorkflow>("is_sales_home_workflow", IsSalesHomeWorkflow);
            writer.WriteStringValue("last_published_date", LastPublishedDate);
            writer.WriteStringValue("last_published_version_id", LastPublishedVersionId);
            writer.WriteStringValue("last_updated_by", LastUpdatedBy);
            writer.WriteStringValue("source", Source);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Slack.OpenApiClient.Models.Step>("steps", Steps);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfPrimitiveValues<string>("trigger_ids", TriggerIds);
            writer.WriteDoubleValue("unpublished_change_count", UnpublishedChangeCount);
            writer.WriteStringValue("workflow_function_id", WorkflowFunctionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
